// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBar: typeof import('./components/common/StatusBar.vue')['default']
    TimetableAction: typeof import('./components/timetable/TimetableAction.vue')['default']
    TimetableBody: typeof import('./components/timetable/TimetableBody.vue')['default']
  }
}

export {}
